categories = {

### Sports ####################################

    'yoga':'fitness',
    'יוגה':'fitness',
    'pilates':'fitness',
    'פילאטיס':'fitness',
    'street':'fitness',
    'סטריט':'fitness',
    'workout':'fitness',
    # 'training':'fitness',
    # 'train':'fitness',
    # 'אימון':'fitness',
    'אימונים':'fitness',
    'אימוני':'fitness',
    'fitness':'fitness',
    'פיטנס':'fitness',
    'sport':'fitness',
    'sports':'fitness',
    'ספורט':'fitness',
    'calistetic':'fitness',
    'calistetics':'fitness',
    'bodyweight':'fitness',
    'משקל גוף':'fitness',
    'ninja':'fitness',
    'נינגה':'fitness',
    'strength':'fitness',
    'strong':'fitness',
    'חיזוק':'fitness',
    'power':'fitness',
    'kettlebell':'fitness',
    'קטלבל':'fitness',
    'ballet':'fitness',
    'meditation':'fitness',
    'meditate':'fitness',
    'mindfulness':'fitness',
    'mindful':'fitness',
    'מדיטציה':'fitness',

### Childen ####################################

    'children':'kids',
    'ילדים':'kids',
    'לילדים':'kids',
    'child':'kids',
    'נוער':'kids',
    'kids':'kids',
    'פעוט':'kids',
    'תינוק': 'kids',
    'storytelling': 'kids',
    'junior': 'kids',


    ### Lectures #####################################

    'lesson': 'lectures',
    'webinar': 'lectures',
    'וובינר': 'lectures',
    'crypto': 'lectures',
    'cryptocurrecy': 'lectures',
    'bootcamp': 'lectures',
    'digitalhealth': 'lectures',
    'react': 'lectures',
    'intelligence': 'lectures',
    'develop': 'lectures',
    'developer': 'lectures',
    'microservice': 'lectures',
    'markets': 'lectures',
    'facebook': 'lectures',
    'instagram': 'lectures',
    'twitter': 'lectures',
    'marketing': 'lectures',
    'linkedin': 'lectures',
    'לינקדאין': 'lectures',
    'פייסבוק': 'lectures',
    'אינסטגרם': 'lectures',
    'טוויטר': 'lectures',
    'לדעת': 'lectures',
    'ניהול': 'lectures',
    'python': 'lectures',
    'pydata': 'lectures',
    'javascript': 'lectures',
    'typescript': 'lectures',
    'js': 'lectures',
    'node.js': 'lectures',
    'C++': 'lectures',
    'C#': 'lectures',
    'debate': 'lectures',
    'debating': 'lectures',
    'vue': 'lectures',
    'environment': 'lectures',
    'סביבה': 'lectures',
    'אקלים': 'lectures',
    'capital': 'lectures',
    'devops': 'lectures',
    'angular': 'lectures',
    'wordpress': 'lectures',
    'linux': 'lectures',
    'debian': 'lectures',
    'חינוך': 'lectures',
    'sales': 'lectures',
    'selling': 'lectures',
    'מחירה': 'lectures',

    ### Science #####################################

    'science': 'lectures',
    'מדע': 'lectures',
    'physics': 'lectures',
    'פיזיקה': 'lectures',
    'chemistry': 'lectures',
    'כימיה': 'lectures',
    'biology': 'lectures',
    'ביולוגיה': 'lectures',
    'geography': 'lectures',
    'גיאוגרפיה': 'lectures',
    'היסטוריה': 'lectures',
    'history': 'lectures',
    'vaccine': 'lectures',
    'vaccination': 'lectures',
    'חיסון': 'lectures',
    'קורונה': 'lectures',
    'corona': 'lectures',
    'virus': 'lectures',
    'coronavirus': 'lectures',
    'corona-virus': 'lectures',
    'covid-19': 'lectures',
    'covid19': 'lectures',
    'covid': 'lectures',
    'וירוס': 'lectures',
    'בריאות': 'lectures',
    'health': 'lectures',
    'crisis': 'lectures',
    'medic': 'lectures',
    'medical': 'lectures',
    'medicine': 'lectures',
    'רפואה': 'lectures',
    'תרופה': 'lectures',
    'class': 'lectures',
    'classroom': 'lectures',
    'כיתה': 'lectures',
    'כיתת': 'lectures',
    'conference': 'lectures',
    'coach': 'lectures',
    'coaching': 'lectures',
    'coaches': 'lectures',
    'מדריך': 'lectures',
    'הדרכה': 'lectures',
    'הדרכת': 'lectures',
    'כתיבה': 'lectures',
    'כתיבת': 'lectures',
    'write': 'lectures',
    'writing': 'lectures',
    'writes': 'lectures',
    'cyber': 'lectures',
    'cybersecurity': 'lectures',
    'cyber-security': 'lectures',
    'סייבר': 'lectures',
    'פודקסט': 'lectures',
    'פודקסאט': 'lectures',
    'podcast': 'lectures',
    'podcasts': 'lectures',
    'podcasting': 'lectures',
    'jewish': 'lectures',
    'יהדות': 'lectures',
    'יהודי': 'lectures',
    'summary': 'lectures',
    'quantum': 'lectures',
    'pandemic': 'lectures',
    'מגפה': 'lectures',

### Education #####################################

    'education': 'lectures',
    'educational': 'lectures',
    'learn': 'lectures',
    'learning': 'lectures',
    'seminar': 'lectures',
    'סמינר': 'lectures',
    'לימוד': 'lectures',
    'לימודי': 'lectures',
    'לימודים': 'lectures',
    'למידה': 'lectures',
    'למידת': 'lectures',
    'knowledge': 'lectures',
    'מידע': 'lectures',
    'tech': 'lectures',
    'technologies': 'lectures',
    'technology': 'lectures',
    'טכנולוגיה': 'lectures',
    'טכנולוגיות': 'lectures',
    'טכנולוגית': 'lectures',
    'טכנולוגיית': 'lectures',
    'passover': 'lectures',
    'פסח': 'lectures',
    'tora': 'lectures',
    'bible': 'lectures',
    'תנך': 'lectures',
    'תורה': 'lectures',
    'פוליטיקה': 'lectures',
    'politics': 'lectures',
    'politically': 'lectures',
    'entrepreneur': 'lectures',
    'entrepreneurs': 'lectures',
    'entrepreneurship': 'lectures',
    'יזם': 'lectures',
    'יוזמה': 'lectures',
    'יזמות': 'lectures',
    'workshop': 'lectures',
    'סדנה': 'lectures',
    'סדנת': 'lectures',
    'שיחה': 'lectures',
    'שיחות': 'lectures',
    'conversation': 'lectures',
    'conversations': 'lectures',
    'talking': 'lectures',
    'talks': 'lectures',
    'talk': 'lectures',
    'מדבר': 'lectures',
    'מדברים': 'lectures',
    'קריירה': 'lectures',
    'career': 'lectures',
    'support': 'lectures',
    'supports': 'lectures',
    'supporting': 'lectures',
    'עזרה': 'lectures',
    'לעזור': 'lectures',
    'עוזר': 'lectures',
    'עוזרת': 'lectures',
    'working': 'lectures',
    'works': 'lectures',
    'עבודה': 'lectures',
    'לעבוד': 'lectures',
    'עובדים': 'lectures',
    'microsoft': 'lectures',
    'google': 'lectures',
    'amazon': 'lectures',
    'cloud': 'lectures',
    'aws': 'lectures',
    'azure': 'lectures',
    'database': 'lectures',
    'sql': 'lectures',
    'frontend': 'lectures',
    'front-end': 'lectures',
    'back-end': 'lectures',
    'development': 'lectures',
    'program': 'lectures',
    'programming': 'lectures',
    'programmer': 'lectures',
    'תכנות': 'lectures',
    'תוכנה': 'lectures',
    'לתכנת': 'lectures',
    'מתכנת': 'lectures',
    'business': 'lectures',
    'עסקים': 'lectures',
    'businesses': 'lectures',
    'סטודנט': 'lectures',
    'סטודנטים': 'lectures',
    'סטודנטיות': 'lectures',
    'student': 'lectures',
    'students': 'lectures',
    'study': 'lectures',
    'studies': 'lectures',
    'studying': 'lectures',
    'interview': 'lectures',
    'interviewing': 'lectures',
    'ראיון': 'lectures',
    'ראיונות': 'lectures',
    'startup': 'lectures',
    'startups': 'lectures',
    'start-up': 'lectures',
    'market': 'lectures',
    'teaching': 'lectures',
    'teach': 'lectures',
    'teacher': 'lectures',
    'teaches': 'lectures',
    'discuss': 'lectures',
    'discussion': 'lectures',
    'discusses': 'lectures',
    'אוניבסיטה': 'lectures',
    'university': 'lectures',
    'school': 'lectures',
    'בית-ספר': 'lectures',
    'innovative': 'lectures',
    'innovation': 'lectures',
    'innovate': 'lectures',
    'leader': 'lectures',
    'leadership': 'lectures',
    'github': 'lectures',
    'hacker': 'lectures',
    'hackers': 'lectures',
    'hackering': 'lectures',
    'האקר': 'lectures',
    'האקרים': 'lectures',
    'נטוורקינג': 'lectures',
    'network': 'lectures',
    'data': 'lectures',
    'lecture': 'lectures',
    'הרצאה': 'lectures',
    'intro': 'lectures',
    'מבוא': 'lectures',
    'investment': 'lectures',
    'השקע': 'lectures',
    'להשקיע': 'lectures',
    'pitch': 'lectures',
    'היי-טק': 'lectures',
    'יזמים': 'lectures',
    'embedded': 'lectures',
    'design': 'lectures',
    'קורס': 'lectures',
    'course': 'lectures',

### Shows #####################################

    'shows': 'fun',
    'הצגה': 'fun',
    'הצגות': 'fun',
    'תאטרון': 'fun',
    'theater': 'fun',
    'הופעה': 'fun',
    'הופעות': 'fun',
    'cooking': 'fun',
    'בישול': 'fun',
    'מבשל': 'fun',
    'מבשלת': 'fun',
    'בישולים': 'fun',
    'בישולי': 'fun',
    'cooks': 'fun',
    'סטנדאפ': 'fun',
    'סטנד-אפ': 'fun',
    'standup': 'fun',
    'stand-up': 'fun',
    'chefs': 'fun',
    'שף': 'fun',
    'שפים': 'fun',
    'happyhour': 'fun',
    'funny': 'fun',
    'כיף': 'fun',
    'כיפי': 'fun',
    'מצחיק': 'fun',
    'צחוק': 'fun',
    'לצחוק': 'fun',
    'צחוקים': 'fun',
    'קפה': 'fun',
    'coffee': 'fun',
    'cafe': 'fun',
    'movie': 'fun',
    'סרט': 'fun',
    'משקה': 'fun',
    'משקאות': 'fun',
    'drink': 'fun',

### Party #####################################

    'party': 'fun',
    'parties': 'fun',
    'celebrat': 'fun',
    'מסיבה': 'fun',
    'מסיבת': 'fun',
    'מסיבות': 'fun',
    'פאב': 'fun',
    'dance': 'fun',
    'dancing': 'fun',
    'ריקוד': 'fun',
    'ריקודים': 'fun',
    'ריקודי': 'fun',
    'דיסקו': 'fun',
    'disco': 'fun',
    'concert': 'fun'

    ###  #####################################
#kids, lectures, fitness, fun, other
}