strictCat = {
    'כוח': 'fitness',
    'בלט': 'fitness',
    'kid': 'kids',
    'ילד': 'kids',
    'jew': 'lectures',
    'ידע': 'lectures',
    'work': 'lectures',
    'job': 'lectures',
    'web': 'lectures',
    'עסק': 'lectures',
    'שוק': 'lectures',
    'hack': 'lectures',
    'ux': 'lectures',
    'xd': 'lectures',
    'ui': 'lectures',
    'sale': 'lectures',
    'sell': 'lectures',
    'cook': 'fun',
    'chef': 'fun',
    'fun': 'fun',
    'show': 'fun',
    'pub': 'fun',
    'techno': 'fun',
    'טכנו': 'fun',
    'sing': 'fun',

}